name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y php-mysql
        composer install

    - name: Set up database schema
      run: |
        mysql -u root -e "CREATE DATABASE mental_health_intake;"
        mysql -u root mental_health_intake < database/schema.sql

    - name: Run tests
      run: |
        vendor/bin/phpunit tests

    - name: Deploy to server
      run: |
        rsync -avz --exclude '.git' --exclude 'tests' . user@server:/path/to/deploy
